make the client script use bash instead of zsh

diff --git a/gjfy-post b/gjfy-post
--- a/gjfy-post
+++ b/gjfy-post
@@ -1,18 +1,22 @@
-#!/bin/zsh
+#!/bin/bash
 
 POSTURL="${GJFY_POSTURL:-http://localhost:9154/api/v1/new}"
 
-whence jq >/dev/null 2>&1 || { print -u2 "jq utility not found"; exit 1 }
+which jq >/dev/null 2>&1 || {
+    echo "jq utility not found" >&2
+    exit 1
+}
+
 if [[ $# -lt 2 ]]
 then
-    print -u2 "usage: $0 <authtoken> <secret>"
+    echo "usage: $0 <authtoken> <secret>" >&2
     exit 2
 fi
 
-if [[ -z $3 ]]
+if [[ -z "$3" ]]
 then
     postdata="{\"auth_token\":\"$1\",\"secret\":\"$2\"}"
 else
     postdata="{\"auth_token\":\"$1\",\"secret\":\"$2\",\"max_clicks\":$3}"
 fi
-curl -s -X POST -d $postdata $POSTURL | jq -r '.url,.api_url,.error | select (.!=null)'
+curl -s -X POST -d "$postdata" "$POSTURL" | jq -r '.url,.api_url,.error | select (.!=null)'
